ConferenceManagement/ConferenceManagement/Models/Listener.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ConferenceManagement.Models
{
    public class Listener
    {
        public long ListenerId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

ConferenceManagement/ConferenceManagement/Models/Session.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ConferenceManagement.Models
{
    public class Session
    {
        public long SessionId { get; set; }
        public string SessionName { get; set; }
        public long ConferenceId { get; set; }
        public long SessionChairId { get; set; }
        public long SpeakerId { get; set; }
        public long RoomId { get; set; }
        public string Time { get; set; }

        public ProgramCommittee ProgramCommittee { get; set; }
        public Author Author { get; set; }
        public Room Room { get; set; }

        //public Cochair sessionChair { get; set; }
        //public List<Speaker> speakers { get; set; }
    }
}

ConferenceManagement/ConferenceManagement/Controllers/ListenerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ConferenceManagement.Repository;
using ConferenceManagement.Models;
using ConferenceManagement.RuntimeObjects;

namespace ConferenceManagement.Controllers
{
    public class ListenerController : Controller
    {
        ProposalDBControl dBControlProposal = new ProposalDBControl();
        DbInstance dbControls = DbInstance.GetDbInstance();
        MockInstance mockRepo = MockInstance.GetDbInstance();

        // GET: Listener
        public ActionResult Index()
        {
            return View();
        }

        // GET: Listener/Sessions
        public ActionResult Sessions()
        {
            List<Session> sessions = dBControlProposal.GetAllSessions();
            return View(sessions);
        }

        // GET: Listener/OneSession/{id}
        public ActionResult OneSession(long id)
        {
            Session session = dBControlProposal.GetSession(id);
            return View(session);
        }

        //GET: Listener/Session
        public ActionResult BuyTicket(long id)
        {
            long sessionId = id;
            long currentListenerId = mockRepo.getCurrentListener().ListenerId;
            dBControlProposal.BuyTicket(sessionId, currentListenerId);

            return RedirectToAction("Sessions");
        }
    }
}

ConferenceManagement/ConferenceManagement/Controllers/SessionController.cs
using ConferenceManagement.Models;
using ConferenceManagement.Repository;
using ConferenceManagement.RuntimeObjects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ConferenceManagement.Controllers
{
    public class SessionController : Controller
    {
        DbInstance dbControls = DbInstance.GetDbInstance();
        ProposalDBControl proposalDbControl = new ProposalDBControl();

        // GET: Session
        public ActionResult Index()
        {
            List<Session> sessions = proposalDbControl.GetAllSessions();
            return View(sessions);
        }

        // GET: Session/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Session/Create
        [HttpPost]
        public ActionResult Create(Session session)
        {
            try
            {
                dbControls.AddSession(session);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ConferenceManagement/ConferenceManagement/Views/Listener/BuyTicket.cshtml
@{
    ViewBag.Title = "BuyTicket";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>You succesfully bought a ticket to this conference!</h1>

<p>
    @Html.ActionLink("Back to Sessions", "Sessions")
</p>

ConferenceManagement/ConferenceManagement/Views/Listener/Index.cshtml
@model ConferenceManagement.Models.Listener

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Hello Listener</h2>

<div>
    @Html.ActionLink("Go to Sessions", "Sessions")
</div>

ConferenceManagement/ConferenceManagement/Views/Listener/OneSession.cshtml
@model ConferenceManagement.Models.Session

@{

    ViewBag.Title = "Session";
    Layout = "~/Views/Shared/_Layout.cshtml";

    long id = (long)Char.GetNumericValue(Context.Request.Path.Last());
}

<h2>Session</h2>

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.SessionName)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.SessionName)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.ConferenceId)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.ConferenceId)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.SessionChairId)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.SessionChairId)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.SpeakerId)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.SpeakerId)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.RoomId)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.RoomId)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Time)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Time)
    </dd>

</dl>

<div>
    <div>
        @Html.ActionLink("Buy ticket", "BuyTicket", "Listener", new { id }, null)
    </div>
    <div>
        @Html.ActionLink("Back to Sessions", "Sessions")
    </div>
</div>

ConferenceManagement/ConferenceManagement/Views/Listener/Sessions.cshtml
@model IEnumerable<ConferenceManagement.Models.Session>

@{
    ViewBag.Title = "Sessions";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ConferenceManagement.Repository.DbControls dbControls = (ConferenceManagement.Repository.DbControls)ViewBag.DbControls;
}

<h2>Sessions</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SessionName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SessionName)
        </td>
  
        <td>
            @Html.ActionLink("Details", "OneSession", new { id=item.SessionId })
        </td>
    </tr>
}

</table>

ConferenceManagement/ConferenceManagement/Views/Listener/Trial.cshtml
@{
    ViewBag.Title = "Trial";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Bought ticket</h2>